export {default as About} from "./about/About"
export {default as Contact} from "./contact/Contact"
export {default as Home} from "./home/Home"
export {default as Menu} from "./menu/Menu"
export {default as Upload} from "./upload/Upload"
export {default as Auth} from "./auth"
