export { default as About } from './about/About'
export { default as Contact } from './contact/Contact'
export { default as Home } from './home/Home'
export { default as Menu } from './menu/Menu'
export { default as Detail } from './detail/Detail'
export { default as Discount } from './discount/Discount'
export { default as LoginForm } from './auth/LoginForm'
export { default as RegisterForm } from './auth/RegisterForm'
