GET http://localhost:5000/posts

###

POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "username": "vhkhuyen2", 
    "password": "vhkhuyen"
}

###
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "username": "vhkhuyen2", 
    "password": "vhkhuyen"
}
###
POST http://localhost:5000/posts/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Mjc5ZGE1ZmRlMmEwMDRlNTJlYmZlMDQiLCJ1c2VybmFtZSI6InZoa2h1eWVuMiIsImlhdCI6MTY1MjE1MjkzNn0.xtMSfpvBf-hUv86RwLY3HHQnPNnqf5GCaN8C2VC8hT8

{
    "title": "Burger",  
    "description": "Minh Anh xinh xeo cute", 
    "image":"https://demo2wpopal.b-cdn.net/poco/wp-content/uploads/2020/08/16-1.png",
    "category": "Foodee"
}
###

PUT  http://localhost:5000/posts/6266c91839b7d89879b0fed4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjY1N2YxYTMzMDJjYjNlM2I0M2Y3MjgiLCJ1c2VybmFtZSI6InZoa2h1eWVuMSIsImlhdCI6MTY1MDkwMzEzN30.HcRdka3E1wY4mAhLaoMEMrOlsapj_WVDcCetB2WERXA


{
    "title": "Sushiiii",  
    "description": "Minh Anh cute phomaique",
    "image":"https://demo2wpopal.b-cdn.net/poco/wp-content/uploads/2020/08/16-1.png",
    "category": "Foodee"
}
###
DELETE http://localhost:5000/posts/6266cacd725e9993342fdee1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjY1N2YxYTMzMDJjYjNlM2I0M2Y3MjgiLCJ1c2VybmFtZSI6InZoa2h1eWVuMSIsImlhdCI6MTY1MDkwMzEzN30.HcRdka3E1wY4mAhLaoMEMrOlsapj_WVDcCetB2WERXA
