GET http://localhost:5000/api/posts
###

POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "vhkhuyen2", 
    "password": "vhkhuyen"
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "vhkhuyen2", 
    "password": "vhkhuyen"
}
###
POST http://localhost:5000/api/posts/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Mjc5ZGE1ZmRlMmEwMDRlNTJlYmZlMDQiLCJ1c2VybmFtZSI6InZoa2h1eWVuMiIsImlhdCI6MTY1MjE1MjkzNn0.xtMSfpvBf-hUv86RwLY3HHQnPNnqf5GCaN8C2VC8hT8

{
    "title": "Burger",  
    "description": "Minh Anh xinh xeo cute", 
    "image":"https://demo2wpopal.b-cdn.net/poco/wp-content/uploads/2020/08/16-1.png",
    "category": "Foodee"
}
